apiVersion: v1
kind: Service
metadata:
  name: {{ include "manifest-socket.fullname" . }}
  labels:
    {{- include "manifest-socket.labels" . | nindent 4 }}
    app: {{ .Values.selector.deployment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.selector.deployment }}
